
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace GadgeteerApp1
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.UsbClientDP usbClientDP;
        Gadgeteer.Modules.GHIElectronics.Button button;
        Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;
        Gadgeteer.Modules.GHIElectronics.Display_HD44780 char_Display;
        Gadgeteer.Modules.GHIElectronics.SDCard sdCard;
        Gadgeteer.Modules.Seeed.Accelerometer accelerometer;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            usbClientDP = new GTM.GHIElectronics.UsbClientDP(1);
		
            accelerometer = new GTM.Seeed.Accelerometer(3);
		
            sdCard = new GTM.GHIElectronics.SDCard(5);
		
            char_Display = new GTM.GHIElectronics.Display_HD44780(6);
		
            button = new GTM.GHIElectronics.Button(8);
		
            temperatureHumidity = new GTM.Seeed.TemperatureHumidity(9);

        }
    }
}
